repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: local
    hooks:
      - id: qa
        name: qa
        entry: task qa:fix
        language: system
        pass_filenames: false
        stages:
          - commit
