version: "3"

tasks:
  default:
    - task: fix
    - task: check

  fix:
    - task: format
    - task: lint
      vars:
        FLAGS: --fix

  check:
    - task: format
      vars:
        FLAGS: --check
    - task: lint
    - task: typecheck
    - task: test


  typecheck:
    - .venv/bin/mypy src/ tests/

  format:
    cmds:
      - .venv/bin/ruff format . {{.FLAGS}}

  lint:
    - .venv/bin/ruff check . {{.FLAGS}}

  test:
    cmds:
      - .venv/bin/pytest .

